# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Stable interfaces shared by AM-DP123 simulation, XR teleop, and hardware."""

from .am_dp123_camera_contract import (
    AM_DP123_CAMERA_BY_NAME,
    AM_DP123_CAMERAS,
    AM_DP123_STEREO_CAMERA_NAMES,
    AmDp123CameraSpec,
    am_dp123_camera_fov_deg,
    am_dp123_stereo_baseline_m,
    require_am_dp123_camera_contract,
)
from .am_dp123_frame_contract import AM_DP123_FRAMES, AmDp123FrameContract
from .am_dp123_joint_contract import (
    AM_DP123_ABSOLUTE_IK_ACTION_DIM,
    AM_DP123_ARM_JOINT_NAMES,
    AM_DP123_CONTROLLED_JOINT_NAMES,
    AM_DP123_HAND_ACTION_SIDE_INDEX,
    AM_DP123_HAND_CLOSED_POSITIONS,
    AM_DP123_HAND_JOINT_NAMES,
    AM_DP123_HAND_OPEN_POSITIONS,
    AM_DP123_HAND_TRIGGER_CLOSED,
    AM_DP123_HAND_TRIGGER_OPEN,
    AM_DP123_HEAD_JOINT_NAMES,
    AM_DP123_HOME_POSITIONS,
    AM_DP123_IK_JOINT_NAMES,
    AM_DP123_JOINT_POSITION_ACTION_DIM,
    AM_DP123_JOINT_SPECS,
    AM_DP123_LEFT_ARM_JOINT_NAMES,
    AM_DP123_LEFT_HAND_JOINT_NAMES,
    AM_DP123_LOCOMOTION_JOINT_NAMES,
    AM_DP123_RIGHT_ARM_JOINT_NAMES,
    AM_DP123_RIGHT_HAND_JOINT_NAMES,
    AM_DP123_STATE_DIM,
    AM_DP123_STATE_JOINT_NAMES,
    AM_DP123_WAIST_JOINT_NAMES,
    AmDp123JointSpec,
    am_dp123_hand_closed_fraction,
    am_dp123_hand_targets,
    require_am_dp123_joint_contract,
    validate_am_dp123_joint_names,
)

__all__ = [
    "AM_DP123_ABSOLUTE_IK_ACTION_DIM",
    "AM_DP123_ARM_JOINT_NAMES",
    "AM_DP123_CAMERAS",
    "AM_DP123_CAMERA_BY_NAME",
    "AM_DP123_CONTROLLED_JOINT_NAMES",
    "AM_DP123_FRAMES",
    "AM_DP123_HAND_ACTION_SIDE_INDEX",
    "AM_DP123_HAND_CLOSED_POSITIONS",
    "AM_DP123_HAND_JOINT_NAMES",
    "AM_DP123_HAND_OPEN_POSITIONS",
    "AM_DP123_HAND_TRIGGER_CLOSED",
    "AM_DP123_HAND_TRIGGER_OPEN",
    "AM_DP123_HEAD_JOINT_NAMES",
    "AM_DP123_HOME_POSITIONS",
    "AM_DP123_IK_JOINT_NAMES",
    "AM_DP123_JOINT_POSITION_ACTION_DIM",
    "AM_DP123_JOINT_SPECS",
    "AM_DP123_LEFT_ARM_JOINT_NAMES",
    "AM_DP123_LEFT_HAND_JOINT_NAMES",
    "AM_DP123_LOCOMOTION_JOINT_NAMES",
    "AM_DP123_RIGHT_ARM_JOINT_NAMES",
    "AM_DP123_RIGHT_HAND_JOINT_NAMES",
    "AM_DP123_STATE_DIM",
    "AM_DP123_STATE_JOINT_NAMES",
    "AM_DP123_STEREO_CAMERA_NAMES",
    "AM_DP123_WAIST_JOINT_NAMES",
    "AmDp123CameraSpec",
    "AmDp123FrameContract",
    "AmDp123JointSpec",
    "am_dp123_camera_fov_deg",
    "am_dp123_hand_closed_fraction",
    "am_dp123_hand_targets",
    "am_dp123_stereo_baseline_m",
    "require_am_dp123_camera_contract",
    "require_am_dp123_joint_contract",
    "validate_am_dp123_joint_names",
]
